### ISSUE TITLE
Cannot create container for service db: Duplicate mount point: /var/lib/mysql

### ISSUE THREAD

**Issue by benkyriakou** [drud/ddev#2386]
**Describe the bug**

When `ddev composer create` tries to recreate the containers it fails with `Duplicate mount point: /var/lib/mysql`

**To Reproduce**

1. `ddev config --project-type=drupal8 --docroot=web --create-docroot`
2. `ddev start`
3. `ddev composer create "drupal/recommended-project:^8"`

This is basically the suggested setup instructions from https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-8-quickstart.

**Expected behavior**

The containers should restart

**Screenshots**

```
Moving installation to project root
Running  Command=ip address show dev docker0
Building db
Building web
Recreating ddev-foo-db ... error

ERROR: for ddev-foo-db  Cannot create container for service db: Duplicate mount point: /var/lib/mysql

ERROR: for db  Cannot create container for service db: Duplicate mount point: /var/lib/mysql
Encountered errors while bringing up the project.
Failed to start project after composer create: Failed to run docker-compose [-f /home/benk/Documents/workspace/misc/foo/.ddev/.ddev-docker-compose-full.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> fe46a4d1a5cf
Step 3/6 : ARG username
 ---> Using cache
 ---> 2a7954324081
Step 4/6 : ARG uid
 ---> Using cache
 ---> 3786c7974b7c
Step 5/6 : ARG gid
 ---> Using cache
 ---> 359907858d46
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 25bda57e7f85

Successfully built 25bda57e7f85
Successfully tagged drud/ddev-dbserver-mariadb-10.2:v1.15.0-foo-built
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> b18fef685762
Step 3/6 : ARG username
 ---> Using cache
 ---> f266e43e8d80
Step 4/6 : ARG uid
 ---> Using cache
 ---> b71757a0592d
Step 5/6 : ARG gid
 ---> Using cache
 ---> 0669661f8741
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 55264701a242

Successfully built 55264701a242
Successfully tagged drud/ddev-webserver:v1.15.0-foo-built
', stderr='Building db
Building web
Recreating ddev-foo-db ... error

ERROR: for ddev-foo-db  Cannot create container for service db: Duplicate mount point: /var/lib/mysql

ERROR: for db  Cannot create container for service db: Duplicate mount point: /var/lib/mysql
Encountered errors while bringing up the project.'
```

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu 19.04
 - Docker version information (use `docker version`) and insert it here.
```
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:59:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:58:31 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information: 1.15.0
 - config.yaml contents for the misbehaving project
```
name: foo
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Comment by rfay** [comment]
I've seen this on Ubuntu before. `ddev poweroff` and `ddev start` fixed it. 

I think it might be a bug fixed in old docker. If you're not using the Docker repositories for your docker install, please do, so you get current. Also, of course, it's time to update your unsupported Ubuntu 19.04. Ubuntu 20.04 is working very well...

**Comment by benkyriakou** [comment]
:+1: I'll give upgrading a go and report back if I still have issues. As you say, ddev seems happy once poked (I just ran `ddev restart`), so I'm not entirely sure why this is an issue with this specific command!

**Comment by rfay** [comment]
Thanks - I hope to hear your report about this. I'm suspecting it's a fixed docker bug. I used to see it a lot more. Can't remember where I saw it the other day.

**Comment by rfay** [comment]
I"m going to close this for now, hoping it's an outdated docker version, happy to continue the conversation here.
