### ISSUE TITLE
Connecting to wrong database: docker-compose v2 is not respecting `links` any more  - ambiguous "db" hostname

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3369]
If multiple DDEV projects are running at the same time, they may try to connect to each other's databases.

docker-compose v2.1.1+ is not respecting the `links` statement any more, so if you use a servicename as a hostname... and more than one project is running, the hostname will be ambiguous, resulting in roundn-robin behavior.

1. It's recommended to all users to use `ddev-<project>-<servicename>` for configurations. So `ddev-<project>-db` for example. In that case you won't have this problem.
2. docker-compose v1 does not have this problem, so uncheck docker-compose v2 in Docker Desktop "Experimental settings" or `docker-compose disable-v2` (these work on macOS/Windows/WSL2 only, not Linux)
3. docker-compose v2 before 2.1.1 does not have this problem - see https://github.com/docker/compose/issues/8935

ddev-webserver ~/.my.cnf uses the ambiguous hostname "db" instead of `ddev-<project>-db` - that's fixed in https://github.com/drud/ddev/pull/3376

So:
- [x] Make sure ~/.my.cnf on ddev-webserver has fullname of container
- [x] This is another docker-compose v2 bug - file it
- [x] Review all ddev-contrib to make sure everything is using the unambiguous naming.

**Comment by wtfred** [comment]
When having multiple project start at the same time, i randomly had errors like this on page refresh :
`TYPO3.CMS.Frontend.Controller.TypoScriptFrontendController": The page is not configured! [type=0][]`

- with docker-compose 2.1.1, when i hit F5, i have errors like 3 times every 5 refresh
- when downgraded to 2.0.1, i refresh like 10-15 times and never got the errors
- fixing my `.env` with `ddev-<projectname>-db` instead of just `db` and upgraded to 2.1.1 : refresh 10-15 times, no errors

(I don't use ddev default `AdditionalConfiguration.php`, i use `disable_settings_management: true` on all my project and have my own `AdditionalConfiguration.php` where i read db values from ENV vars)

**Comment by jonaseberle** [comment]
I am using docker-compose v1 in production without any `links` with identical `docker-compose.yaml` in multiple directories (aka different projects). 

I have a pretty similar setup to `ddev` with a frontend proxy and an additional "external" network where the frontend proxy and some containers are in. (I am mentioning that because that might be were project-local name resolution gets now overridden in v2?)

I am accessing project-local containers with only their service name. There has not been any ambiguity in name resolution. 
We would have noticed for sure because all these projects have the same services and are used actively.

If that change has not been communicated by the docker-compose maintainers (and it looks to me like that since examples like https://docs.docker.com/compose/gettingstarted/#step-1-setup and https://docs.docker.com/samples/#sample-applications are relying on service name=host name resolution) I think this must be a bug/missing feature in docker-compose v2.

**Comment by rfay** [comment]
Thanks for your help. Filed docker-compose issue in https://github.com/docker/compose/issues/8935

**Comment by rfay** [comment]
#3376 fixed the minor problem of ddev-webserver's ~/.my.cnf, the big issue here is https://github.com/docker/compose/issues/8935

**Comment by rfay** [comment]
Review of usages in docker-compose done in https://github.com/drud/ddev-contrib/pull/176

**Comment by Konafets** [comment]
I just faced the same error and was able to "downgrade" docker-compose on Mac via the "Docker Desktop" preferences:

![2021-11-24_12-07-32](https://user-images.githubusercontent.com/363363/143227932-83fef2f2-3c09-4fce-ae14-9c2673e62bc1.jpg)

**Comment by rfay** [comment]
Yes, or on Windows/WSL2/macOS `docker-compose disable-v2`

**Comment by rfay** [comment]
https://github.com/docker/compose/issues/8935 is claimed fixed in an upcoming version; the current 2.2.0/2.2.1 are completely broken for other reasons
* https://github.com/drud/ddev/issues/3404

**Comment by rfay** [comment]
This is fixed in today's (coming) ddev v1.18.2, which embeds docker-compose 2.2.2, which doesn't have this problem.

**Comment by adrian-cid** [comment]
I have ddev version 1.21.6 and docker compose 2.19.1 and I'm still facing this issue.

**Comment by rfay** [comment]
@adrian-cid I doubt that you have this issue, as DDEV no longer uses your docker-compose binary. Please upgrade to DDEV v1.22.0, and please open a new issue with the full details of the problem you're having. We'll be happy to help!

**Comment by adrian-cid** [comment]
@rfay thanks, I updated ddev to the latest version v.1.22.0 and it seems to be working now well, by the way, congrats on the Aaron Winborn Award and I'm still maintaining your https://www.drupal.org/project/no_autocomplete drupal module.

**Comment by rfay** [comment]
Yay! - Thanks for the congrats, and wow, I have no memory of no_autocomplete at all! Was just looking at it. Thanks for taking care of that over the years!
