### ISSUE TITLE
Improve php.ini/mailhog configuration in nginx-php-fpm7-local container

### ISSUE THREAD

**Issue by rfay** [drud/ddev#70]
_From @rfay on March 14, 2017 23:24_

## What happened (or feature request):

After a `ddev start` followed by install of a wordpress site, I see this in the php7.0-fpm.log  :

```
root@d840fcd40125:/var/log# tail php7.0-fpm.log
[14-Mar-2017 22:36:11] NOTICE: fpm is running, pid 18
[14-Mar-2017 22:36:11] NOTICE: ready to handle connections
[14-Mar-2017 22:36:11] NOTICE: systemd monitor interval set to 10000ms
[14-Mar-2017 22:36:50] WARNING: [pool www] child 28 said into stderr: "sh: 1: "
[14-Mar-2017 22:36:50] WARNING: [pool www] child 28 said into stderr: "/usr/sbin/sendmail: not found"
[14-Mar-2017 22:36:50] WARNING: [pool www] child 28 said into stderr: ""
root@d840fcd40125:/var/log#
```

## What you expected to happen: 

php.ini should be configured to use Mailhog to deliver mail, not use /usr/sbin/sendmail

## How to reproduce it (as minimally and precisely as possible):

1. `ddev start` with drudio repo
2. Hit the site and do an install
3. View the /var/log/php7.0-fpm.log

This was encountered while testing https://github.com/drud/ddev/pull/65

_Copied from original issue: drud/general#84_

**Comment by rickmanelius** [comment]
@rfay I believe this is fixed. I just tested sending an email and I'm not seeing that error appear and I was able to confirm that mailhog is currently in charge of sending emails.

**Comment by rfay** [comment]
I agree it's probably fixed, I'd rather know where, of course. 

We still see this:
`[03-May-2017 20:56:33] WARNING: [pool www] child 20 said into stderr: "127.0.0.1:1025 nobody@ba6da0d38050"`

BUT, mailhog is working and it looks pretty OK.
